name: Deploy Frontend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build Next.js
        run: |
          cd frontend
          npm run build

      # LOGIN TO AZURE
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_755CB624CE19401A943806CB4B451DF5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_81C66415FAB747C882E6C57C94D5ED1A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_24588C6CE82B467DA7886CBFDEC76A2F }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ecommerce-frontend-kirethik
          slot-name: Production
          package: frontend
